# Generated by Django 4.1.7 on 2023-03-07 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_resume', models.FileField(upload_to='resume')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=32)),
                ('job_description', models.TextField()),
                ('job_type', models.CharField(choices=[('PT', 'Part Time'), ('FT', 'Full Time'), ('RE', 'Remote'), ('CT', 'contract')], default='FT', max_length=2)),
                ('job_location', models.CharField(max_length=50)),
                ('job_salary', models.PositiveBigIntegerField()),
                ('job_posted_date', models.DateTimeField(auto_now_add=True)),
                ('job_expiry_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_company_name', models.CharField(max_length=35)),
                ('employer_description', models.TextField()),
                ('employer_website', models.URLField(blank=True)),
                ('employer_phone_number', models.PositiveBigIntegerField()),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_date', models.DateField(auto_now_add=True)),
                ('Applicants_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.applicants')),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.jobs')),
            ],
        ),
    ]
