# Generated by Django 4.1.7 on 2023-03-07 23:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicants',
            new_name='Applicant',
        ),
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
        migrations.RenameModel(
            old_name='Employers',
            new_name='Employer',
        ),
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
